### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by systemadmin-jschroder** [jenschristianschroder/CPAL-Site-Inspection-Canvas-App#3]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta content="text/html; charset=Windows-1252"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="DA" link="#0563C1" vlink="#954F72" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Cannot trigger github action</p><p class="MsoNormal">&nbsp;</p><table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0" width="600" style="width:450.0pt; border-collapse:collapse"><tbody><tr><td style="padding:0cm 0cm 0cm 0cm"><p class="MsoNormal"><b><span lang="EN-US" style="">Jens Christian Schrøder</span></b></p><p class="MsoNormal"><span lang="EN-US" style="">Technical Specialist – Dynamics 365 CE Platform</span></p><p class="MsoNormal"><span style="">Mobile: +45 29 22 95 98</span></p><p class="MsoNormal"><span style=""><a href="mailto:jens.schroder@microsoft.com"><span style="color:#0563C1">jens.schroder@microsoft.com</span></a> </span></p></td></tr></tbody></table><p class="MsoNormal"><span style=""><img border="0" width="80" height="22" id="Picture_x0020_1" src="cid:image003.jpg@01D69E3E.D9F06660" alt="Microsoft" style="width:.8333in; height:.2291in"></span><span style=""></span></p><p class="MsoNormal">&nbsp;</p></div></body></html>

**Comment by jenschristianschroder** [comment]
This should be fixed :)
